unstable_features = true
binop_separator = "Back"
blank_lines_lower_bound = 1
blank_lines_upper_bound = 1
brace_style = "SameLineWhere"
combine_control_expr = false
control_brace_style = "AlwaysSameLine"
edition = "2018"
empty_item_single_line = true
enum_discrim_align_threshold = 50
fn_single_line = true
force_explicit_abi = true
force_multiline_blocks = true
format_code_in_doc_comments = true
format_macro_matchers = true
format_macro_bodies = true
format_strings = true
hard_tabs = false
imports_indent = "Block"
imports_layout = "HorizontalVertical"
indent_style = "Block"
inline_attribute_width = 0
license_template_path = ".copyright"
match_arm_blocks = true
match_arm_leading_pipes = "Never"
match_block_trailing_comma = true
max_width = 100
merge_derives = true
merge_imports = true
newline_style = "Native"
normalize_comments = true
normalize_doc_attributes = true
#preserve_block_start_blank_lines = true
#preserve_closure_block_wrapping = true
overflow_delimited_expr = true
remove_nested_parens = true
reorder_impl_items = true
reorder_imports = true
group_imports = "StdExternalCrate"
reorder_modules = true
space_after_colon = false
space_before_colon = false
#space_before_fn_sig_paren = true
spaces_around_ranges = true
#space_around_attr_eq = true
struct_field_align_threshold = 50
struct_lit_single_line = false
tab_spaces = 4
trailing_comma = "Always"
trailing_semicolon = false
type_punctuation_density = "Wide"
use_field_init_shorthand = true
use_try_shorthand = true
where_single_line = true
wrap_comments = true

