name: Build
on:
  push:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # leave empty for /
      PUBLIC_URL_PREFIX: ""

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

#      - name: Create firebase-config.json
#        shell: bash
#        run: |
#          cat > ./static/firebase-config.json << __HERE__
#          {
#            apiKey: "${{ secrets.FIREBASE_APIKEY }}",
#            authDomain: "${{ secrets.FIREBASE_AUTH_DOMAIN }}",
#            projectId: "${{ secrets.FIREBASE_PROJECT_ID }}",
#            storageBucket: "${{ secrets.FIREBASE_STORAGE_BUCKET }}",
#            messagingSenderId: "${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}",
#            appId: "${{ secrets.FIREBASE_APP_ID }}",
#            measurementId: "${{ secrets.FIREBASE_MEASUREMENT_ID }}"
#          }
#          __HERE__
#          cat ./static/firebase-config.json

      - name: Install Trunk
#       Install the trunk utility: https://github.com/thedodd/trunk
        run: |
          cargo install trunk wasm-bindgen-cli

      - name: Build with Trunk
        run: |
          trunk build --release

      - name: Deploy to Firebase - https://nirvana.agnos.ai
        if: github.ref == 'refs/heads/main'
        uses: siku2/action-hosting-deploy@v0
        with:
          targets: ${{ secrets.FIREBASE_PROJECT_ID }}
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NIRVANA_DEV_12345 }}'
          channelId: live

      - name: Deploy to Firebase Preview Channel
        if: github.ref != 'refs/heads/main'
        uses: siku2/action-hosting-deploy@v0
        with:
          targets: ${{ secrets.FIREBASE_PROJECT_ID }}
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NIRVANA_DEV_12345 }}'
          expires: 7d
          channelId: preview
