name: Build
on:
  push:
    branches: [main]

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # leave empty for /
      PUBLIC_URL_PREFIX: ""

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Install Trunk
#       Install the trunk utility: https://github.com/thedodd/trunk
        run: |
          set -x
          cargo install trunk wasm-bindgen-cli

      - name: Build with Trunk
        run: |
          set -x
          cargo build
          cd ./static
          trunk build --release
          cd ..
          find ./dist

      - name: Deploy to Firebase
        uses: siku2/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NIRVANA_DEV_12345 }}'
          expires: 30d
          projectId: nirvana-dev-12345
          channelId: live
          targets: examples
