name: Build
on:
  push:
    branches:
      - '**'

jobs:
  publish:
    runs-on: ubuntu-latest
    env:
      # leave empty for /
      PUBLIC_URL_PREFIX: ""

    steps:
      - uses: actions/checkout@v2

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          target: wasm32-unknown-unknown
          override: true
          profile: minimal

      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: cargo-${{ runner.os }}-${{ hashFiles('**/Cargo.toml') }}
          restore-keys: |
            cargo-${{ runner.os }}-

      - name: Install Tools
        run: |
          cargo install wasm-bindgen-cli

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: 14

      - name: Install npm dependencies
        run: npm installs

      - name: Build with npm
        run: npm run build

      - name: Deploy to Firebase - https://nirvana.agnos.ai
        if: github.ref == 'refs/heads/main'
        uses: siku2/action-hosting-deploy@v0
        with:
          targets: ${{ secrets.FIREBASE_PROJECT_ID }}
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NIRVANA_DEV_12345 }}'
          channelId: live

      - name: Deploy to Firebase Preview Channel
        if: github.ref != 'refs/heads/main'
        uses: siku2/action-hosting-deploy@v0
        with:
          targets: ${{ secrets.FIREBASE_PROJECT_ID }}
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_NIRVANA_DEV_12345 }}'
          expires: 7d
          channelId: preview
